/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Newform;

import DAO.DaoNhanVien;
import Entity.ChiTietDonHang;
import Entity.NhanVien1;
import Util.Auth;
import Util.DateHelper;
import Util.MsgBox;
import Util.XDate;
import Util.XImage;
import com.toedter.calendar.JDateChooser;
import java.io.File;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class NhanVienPain extends javax.swing.JPanel {

    DaoNhanVien dao = new DaoNhanVien();
    int row = 0;
    JDateChooser dateChooser = new JDateChooser();
    JFileChooser filechooser = new JFileChooser();

    public NhanVienPain() {
        initComponents();
        this.updateStatus();
        this.filltable();
        String MaNV = (String) tblnv.getValueAt(row, 1);
        NhanVien1 nh = dao.selectById(MaNV);
        tblnv.setRowSelectionInterval(0, 0);
        this.setform(nh);
        this.Total();
        
    }

    private void updateStatus() {
        boolean edit = this.row >= 0;
        boolean first = this.row == 0;
        boolean last = this.row == tblnv.getRowCount() - 1;
        if (!Auth.isManager()) {
            Btnthem.setEnabled(false);
            clean.setEnabled(false);
            Btnxoa.setEnabled(false);
            btnSua.setEnabled(false);
//           
        } else {

            Btnthem.setEnabled(true);
            clean.setEnabled(true);
            Btnxoa.setEnabled(true);
            btnSua.setEnabled(true);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblnv = new javax.swing.JTable();
        BtnTim = new javax.swing.JButton();
        txtTim = new javax.swing.JTextField();
        txtTongnv = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Manv = new javax.swing.JTextField();
        txtmk1 = new javax.swing.JPasswordField();
        txtmk2 = new javax.swing.JPasswordField();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtsdt = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        TxtDC = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        Txtemail = new javax.swing.JTextField();
        Txtdate = new javax.swing.JTextField();
        lblimg = new javax.swing.JLabel();
        txtho = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        rdocon = new javax.swing.JRadioButton();
        rdonghi = new javax.swing.JRadioButton();
        rdonam = new javax.swing.JRadioButton();
        rdonu = new javax.swing.JRadioButton();
        Rdoql = new javax.swing.JRadioButton();
        rdonv = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Btnthem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        Btnxoa = new javax.swing.JButton();
        clean = new javax.swing.JButton();

        setBackground(new java.awt.Color(128, 188, 179));

        jPanel6.setBackground(new java.awt.Color(128, 188, 179));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 127, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        tblnv.setBorder(new javax.swing.border.MatteBorder(null));
        tblnv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã nhân viên", "Họ", "Tên", "Số điện thoại", "Email", "Địa Chỉ", "Ngày Sinh", "Vai trò", "Trạng thái", "Giới tính"
            }
        ));
        tblnv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblnvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblnv);

        BtnTim.setText("Tìm");
        BtnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTimActionPerformed(evt);
            }
        });

        txtTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimActionPerformed(evt);
            }
        });

        txtTongnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongnvActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/Icon/icLast.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/Icon/icFirst.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/Icon/right-arrow-circle_icon-icons.com_53897.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/Icon/back-arrow_icon-icons.com_54057.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTongnv, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTongnv)
                    .addComponent(txtTim)
                    .addComponent(BtnTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel25.setText("Mã nhân viên:");

        jLabel26.setText("Mật khẩu:");

        Manv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManvTxtmanvActionPerformed(evt);
            }
        });

        jLabel28.setText("Xác nhận mật khẩu:");

        jLabel31.setText("Họ tên:");

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnametxtHoActionPerformed(evt);
            }
        });

        jLabel32.setText("Số điện thoại:");

        txtsdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsdtTxtSdtActionPerformed(evt);
            }
        });

        jLabel33.setText("Địa chỉ:");

        TxtDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDCTxtDiachiActionPerformed(evt);
            }
        });

        jLabel34.setText("Ngày sinh:");

        jLabel35.setText("Email:");

        Txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtemailTxtEmailActionPerformed(evt);
            }
        });

        Txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtdateTxtNgaysinhActionPerformed(evt);
            }
        });

        lblimg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/Icon/landscape-image_icon-icons.com_53961.png"))); // NOI18N
        lblimg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblimg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimglblHinhMouseClicked(evt);
            }
        });

        txtho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthotxtHoActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel29.setText("Vai trò:");

        jLabel27.setText("Trạng thái:");

        jLabel30.setText("Giới tính:");

        buttonGroup3.add(rdocon);
        rdocon.setText("Còn làm việc");
        rdocon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoconRdoDangLamActionPerformed(evt);
            }
        });

        buttonGroup3.add(rdonghi);
        rdonghi.setText("Đã nghỉ");

        buttonGroup2.add(rdonam);
        rdonam.setText("Nam");
        rdonam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdonamRdoNamActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdonu);
        rdonu.setText("Nữ");
        rdonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdonuActionPerformed(evt);
            }
        });

        buttonGroup1.add(Rdoql);
        Rdoql.setText("Quản lí");
        Rdoql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdoqlRdoQLActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdonv);
        rdonv.setText("Nhân viên");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(10, 10, 10)
                        .addComponent(rdocon, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(rdonghi, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rdonam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Rdoql, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdonu, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdonv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(Rdoql)
                    .addComponent(rdonv))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(rdonam)
                    .addComponent(rdonu))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(rdocon)
                    .addComponent(rdonghi)))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel35)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtmk2)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(Txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtmk1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Manv, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblimg, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 83, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(txtho, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TxtDC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Txtdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblimg, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Manv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(txtmk2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtmk1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(Txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(TxtDC, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(Txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("QUẢN LÍ NHÂN VIÊN ");

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        Btnthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/Icon/add_insert_new_plus_button_icon_142943.png"))); // NOI18N
        Btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnthemActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/Icon/emblemsynchronizing_93485.png"))); // NOI18N
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        Btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/Icon/seo-social-web-network-internet_262_icon-icons.com_61518.png"))); // NOI18N
        Btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnxoaActionPerformed(evt);
            }
        });

        clean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/Icon/add-new-document_icon-icons.com_54068.png"))); // NOI18N
        clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(clean, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btnxoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btnthem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(Btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(clean, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(526, 526, 526)
                        .addComponent(jLabel1)))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ManvTxtmanvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManvTxtmanvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManvTxtmanvActionPerformed

    private void RdoqlRdoQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdoqlRdoQLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdoqlRdoQLActionPerformed

    private void rdoconRdoDangLamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoconRdoDangLamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoconRdoDangLamActionPerformed

    private void rdonamRdoNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdonamRdoNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdonamRdoNamActionPerformed

    private void txtnametxtHoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnametxtHoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnametxtHoActionPerformed

    private void txtsdtTxtSdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsdtTxtSdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsdtTxtSdtActionPerformed

    private void TxtDCTxtDiachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDCTxtDiachiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDCTxtDiachiActionPerformed

    private void TxtemailTxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtemailTxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtemailTxtEmailActionPerformed

    private void TxtdateTxtNgaysinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtdateTxtNgaysinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtdateTxtNgaysinhActionPerformed

    private void lblimglblHinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimglblHinhMouseClicked
        if (evt.getClickCount() == 2) {

            ChonAnh();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_lblimglblHinhMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        update();       // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

    private void BtnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnxoaActionPerformed
        delete();
        Total();
    }//GEN-LAST:event_BtnxoaActionPerformed

    private void cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanActionPerformed
        clearForm();        // TODO add your handling code here:
    }//GEN-LAST:event_cleanActionPerformed

    private void BtnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTimActionPerformed

        this.keyword();

        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTimActionPerformed

    private void tblnvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblnvMouseClicked
        this.row = tblnv.rowAtPoint(evt.getPoint());
        edit();
    }//GEN-LAST:event_tblnvMouseClicked

    private void txthotxtHoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthotxtHoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthotxtHoActionPerformed

    private void rdonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdonuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdonuActionPerformed

    private void BtnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnthemActionPerformed
        insert();
        Total();// TODO add your handling code here:
    }//GEN-LAST:event_BtnthemActionPerformed

    private void txtTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimActionPerformed

    private void txtTongnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongnvActionPerformed
      
    }//GEN-LAST:event_txtTongnvActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if (row > 0) {
            row--;
            edit();
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        row = 0;
        edit();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (row < tblnv.getRowCount() - 1) {
            row++;
            edit();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        row = tblnv.getRowCount() - 1;
        edit();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnTim;
    private javax.swing.JButton Btnthem;
    private javax.swing.JButton Btnxoa;
    private javax.swing.JTextField Manv;
    private javax.swing.JRadioButton Rdoql;
    private javax.swing.JTextField TxtDC;
    private javax.swing.JTextField Txtdate;
    private javax.swing.JTextField Txtemail;
    private javax.swing.JButton btnSua;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton clean;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblimg;
    private javax.swing.JRadioButton rdocon;
    private javax.swing.JRadioButton rdonam;
    private javax.swing.JRadioButton rdonghi;
    private javax.swing.JRadioButton rdonu;
    private javax.swing.JRadioButton rdonv;
    private javax.swing.JTable tblnv;
    private javax.swing.JTextField txtTim;
    private javax.swing.JTextField txtTongnv;
    private javax.swing.JTextField txtho;
    private javax.swing.JPasswordField txtmk1;
    private javax.swing.JPasswordField txtmk2;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtsdt;
    // End of variables declaration//GEN-END:variables

    private boolean isValidInput(NhanVien1 nv, String confirmPass) {
        if (nv.getTen().isEmpty()) {
            MsgBox.alert(this, "Vui lòng nhập tên!");
            return false;
        }

        if (nv.getDiaChi().isEmpty()) {
            MsgBox.alert(this, "Vui lòng nhập địa chỉ!");
            return false;
        }

        if (nv.getEmail().isEmpty() || !nv.getEmail().matches(".+@.+\\..+")) {
            MsgBox.alert(this, "Vui lòng nhập đúng định dạng email!");
            return false;
        }

        if (nv.getMatKhau().isEmpty()) {
            MsgBox.alert(this, "Vui lòng nhập mật khẩu!");
            return false;
        }

        if (confirmPass.isEmpty()) {
            MsgBox.alert(this, "Vui lòng xác nhận mật khẩu!");
            return false;
        }

        if (!confirmPass.equals(nv.getMatKhau())) {
            MsgBox.alert(this, "Xác nhận mật khẩu không đúng!");
            return false;
        }

        if (nv.getSoDT().isEmpty() || !nv.getSoDT().matches("\\d+")) {
            MsgBox.alert(this, "Vui lòng nhập số điện thoại hợp lệ!");
            return false;
        }

        if (nv.getMaNV().isEmpty()) {
            MsgBox.alert(this, "Vui lòng nhập mã nhân viên!");
            return false;
        }

        if (lblimg.getToolTipText().isEmpty()) {
            MsgBox.alert(this, "Vui lòng chọn hình ảnh!");
            return false;
        }

        if (nv.getNgaySinh() == null) {
            MsgBox.alert(this, "Vui lòng chọn ngày sinh!");
            return false;
        }

        Date currentDate = XDate.getCurrentDate();
        Date ngaySinh = nv.getNgaySinh();

        // Check if ngaySinh is after the current date
        if (!XDate.isDateBefore(ngaySinh, currentDate)) {
            MsgBox.alert(this, "Ngày sinh phải nhỏ hơn ngày hiện tại!");
            return false;
        }

        // Continue with the remaining validations...
        if (nv.getGioiTinh() == null) {
            MsgBox.alert(this, "Vui lòng chọn giới tính!");
            return false;
        }

        return true;
    }

    void insert() {
        NhanVien1 nv = this.getForm();
        String mk2 = new String(txtmk2.getPassword());

        // Kiểm tra điều kiện nhập liệu
        if (isValidInput(nv, mk2)) {
            try {
                dao.insert(nv); // thêm mới
                this.filltable(); // đổ lại bảng
                this.clearForm(); // xóa trắng form
                MsgBox.alert(this, "Thêm mới thành công!");
            } catch (Exception e) {
                MsgBox.alert(this, "Thêm mới thất bại!");
                e.printStackTrace();
            }
        }
    }

    void filltable() {
        DefaultTableModel model = (DefaultTableModel) tblnv.getModel();
        model.setRowCount(0);
        try {
            List<NhanVien1> list = dao.selectAll();

            for (NhanVien1 nv : list) {
                Object[] row = {
                    //                    nv.getSTT(),
                    nv.getSTT(),
                    nv.getMaNV(), // Thêm mã nhân viên
                    nv.getHoVaTenLot(), // Thêm họ và tên lót
                    nv.getTen(), // Thêm tên
                    nv.getSoDT(), // Thêm số điện thoại
                    nv.getEmail(), // Thêm email
                    nv.getDiaChi(), // Thêm địa chỉ
                    DateHelper.toString(nv.getNgaySinh()),
                    nv.isVaiTro() ? "QL" : "NV", // Hiển thị VaiTro dưới dạng "Có" hoặc "Không"
                    nv.isTrangThaiLamViec() ? "Đang làm việc" : "Nghỉ việc", // Hiển thị trạng thái làm việc
                    nv.getGioiTinh(),
                    nv.getHinh(), // Thêm hình
                    nv.getMatKhau(), // Thêm mật khẩu
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void keyword() {
        DefaultTableModel model = (DefaultTableModel) tblnv.getModel();
        model.setRowCount(0);
        String search = txtTim.getText();
        try {
            List<NhanVien1> list = dao.searchByKeyword(search);

            for (NhanVien1 nv : list) {
                Object[] row = {
                    nv.getMaNV(), // Thêm mã nhân viên
                    nv.getHoVaTenLot(), // Thêm họ và tên lót
                    nv.getTen(), // Thêm tên
                    nv.getSoDT(), // Thêm số điện thoại
                    nv.getEmail(), // Thêm email
                    nv.getDiaChi(), // Thêm địa chỉ
                    DateHelper.toString(nv.getNgaySinh()),
                    nv.isVaiTro() ? "QL" : "NV", // Hiển thị VaiTro dưới dạng "Có" hoặc "Không"
                    nv.isTrangThaiLamViec() ? "Đang làm việc" : "Nghỉ việc", // Hiển thị trạng thái làm việc
                    nv.getGioiTinh(),
                    nv.getHinh(), // Thêm hình
                    nv.getMatKhau()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void setform(NhanVien1 nv) {
        txtname.setText(nv.getTen());
        txtho.setText(nv.getHoVaTenLot());
        TxtDC.setText(nv.getDiaChi());
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Txtdate.setText(sdf.format(nv.getNgaySinh()));
        txtmk1.setText(String.valueOf(nv.getMatKhau()));
        txtmk2.setText(String.valueOf(nv.getMatKhau()));
        txtsdt.setText(String.valueOf(nv.getSoDT()));
        Manv.setText(nv.getMaNV());
        lblimg.setText(nv.getHinh());

        if (nv.getHinh() != null) {
            lblimg.setToolTipText(nv.getHinh());
            ImageIcon imageIcon = XImage.read(nv.getHinh());
            lblimg.setIcon(imageIcon);
        }

        if (nv.isVaiTro()) {
            Rdoql.setSelected(true);
            this.rdonv.setSelected(false);
        } else {
            Rdoql.setSelected(false);
            rdonv.setSelected(true);
        }

        if ("Nam".equals(nv.getGioiTinh())) {
            rdonam.setSelected(true);
            rdonu.setSelected(false);
        } else {
            rdonam.setSelected(false);
            rdonu.setSelected(true);
        }
        Txtemail.setText(nv.getEmail());

        // Set giá trị cho RadioButton trạng thái làm việc
        if (nv.isTrangThaiLamViec()) {
            rdocon.setSelected(true);
            rdonghi.setSelected(false);
        } else {
            rdocon.setSelected(false);
            rdonghi.setSelected(true);
        }
    }

    NhanVien1 getForm() {
        NhanVien1 nv = new NhanVien1();
        // Lấy thông tin từ các trường nhập liệu
        nv.setHoVaTenLot(txtho.getText());
        nv.setTen(txtname.getText());
        nv.setDiaChi(TxtDC.getText());
        nv.setHinh(lblimg.getToolTipText());
        nv.setMatKhau(new String(txtmk1.getPassword()));

        // Lấy ngày sinh từ JDateChooser
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        try {
            Date ngaySinh = sdf.parse(Txtdate.getText());
            nv.setNgaySinh(ngaySinh);
        } catch (ParseException e) {
            // Xử lý lỗi khi không thể chuyển đổi ngày tháng
        }
        // Lấy giới tính từ RadioButton
        if (rdonam.isSelected()) {
            nv.setGioiTinh("Nam");
        } else {
            nv.setGioiTinh("Nữ");
        }

        // Lấy thông tin mật khẩu từ JPasswordField
        nv.setMatKhau(new String(txtmk1.getPassword()));

        // Lấy thông tin khác
        nv.setSoDT(txtsdt.getText());
        nv.setMaNV(Manv.getText());
        nv.setEmail(Txtemail.getText());

        // Kiểm tra RadioButton để thiết lập vaiTro
        if (Rdoql.isSelected()) {
            nv.setVaiTro(true);
        } else {
            nv.setVaiTro(false);
        }

        // Set giá trị cho trạng thái làm việc
        nv.setTrangThaiLamViec(rdocon.isSelected());

        return nv;
    }

    void edit() {
        String manv = (String) tblnv.getValueAt(this.row, 1);
        NhanVien1 nv = dao.selectById(manv);
        this.setform(nv);
        tblnv.setRowSelectionInterval(row, row);
//        this.updateStatus();
    }

    void ChonAnh() {
        if (filechooser.showOpenDialog(this) == filechooser.APPROVE_OPTION) {
            File file = filechooser.getSelectedFile();
            XImage.Save(file);
            ImageIcon icon = XImage.read(file.getName());
            lblimg.setIcon(icon);
            lblimg.setToolTipText(file.getName());
        }

    }

    private void Total() {
        filltable();
        int count = 0;
        if (tblnv.getRowCount() > 0) {
            count = tblnv.getRowCount();
            txtTongnv.setText("Tổng số nhân viên: " + Integer.toString(count));
        } else {
            txtTongnv.setText("Tổng số nhân viên: 0");
        }

    }

    void update() {
        NhanVien1 nv = this.getForm();
        String mk2 = new String(txtmk2.getPassword());

        // Kiểm tra điều kiện nhập liệu
        if (isValidInput(nv, mk2)) {
            try {
                dao.update(nv); // thêm mới
                this.filltable(); // đổ lại bảng
                this.clearForm(); // xóa trắng form
                MsgBox.alert(this, "Cập nhật thành công!");
            } catch (Exception e) {
                MsgBox.alert(this, "Cập nhật thất bại!");
                e.printStackTrace();
            }
        }
    }

    void delete() {
        String manv = Manv.getText();

        if (manv == null) {
            MsgBox.alert(this, "Chưa chọn nhân viên cần xóa!");
        } else {
            if (MsgBox.confirm(this, "Bạn thực sự muốn xóa nhân viên này?")) {
                try {
                    dao.delete(manv); // xóa
                    // đổ lại bảng
                    this.clearForm(); // clear form
                    MsgBox.alert(this, "Xóa thành công!");
                } catch (Exception e) {
                    MsgBox.alert(this, "Xóa thất bại!");
                }
            }
        }
    }

    private void clearForm() {
        txtname.setText("");
        TxtDC.setText("");
        dateChooser.setDate(null); // Xóa ngày sinh trên JDateChooser
        Txtemail.setText("");
        txtmk1.setText("");
        txtmk2.setText("");
        txtho.setText("");
        txtsdt.setText("");
        Manv.setText("");
        lblimg.setText(""); // Xóa đường dẫn hình ảnh
        lblimg.setIcon(null); // Xóa hình ảnh hiển thị
        Rdoql.setSelected(false);
        rdocon.setSelected(false); // Bỏ chọn cả hai RadioButton
        Txtdate.setText(null);

    }

}
